<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\EntityRepository;
/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
    public function getEntityManager()
    {
        return parent::getEntityManager();
    }
}
